---
title: "The Effects of Microplastics (MP) on the Foraging Success of Sanderlings Calidris alba"
author: "Nicky Tumbale"
date: "3/10/25"
output:
  pdf_document: default
  html_document: default
---

  The increasing presence of microplastics (MP) in coastal ecosystems has raised concerns about their potential
impacts on wildlife, particularly in coastal environments. Microplastics in marine environments originate
through runoff, wastewater effluent, and atmospheric deposition (Frias & Nash, 2019; Moore et al., 2002).
These polutants can accumulate in beach sediments and in the digestive systems of filter-feeding inverte-
brates, such as Pacific mole crabs (Emerita analoga), a key prey species for shorebirds like the sanderling
(Calidris alba)(Horn et al., 2019; Jeong et al., 2024). Prior research in the Stillman lab suggests that mi-
croplastic ingestion may negaticely impact invertebrate prey by decreasing their burrowing ability (Matthews,
2022), potentially affecting predator-prey dynamics in sandy beach ecosystems. However, the direct effects
of microplastic contamination on the foraging success of sanderlings remain unexplored.
  This study aims to investigate how microplastic contamination in sand, water, and prey influences the
foraging success of sanderlings along the Northern California coast. Given that microplastic exposure has
been linked to reduced burrowing ability in Pacific mole crabs, I hypothesize that sanderlings will exhibit
higher foraging success in areas with greater microplastic concentrations due to increased prey accessibility.
To test this, I will quantify microplastic abundance in environmental samples and prey items to across a
gradient of pollution levels through density separation and examination under a fluorescence microscope in
the CMIC. I will be simultaneously assessing sanderling foraging rates through video recordings. Foraging
success will be quantified by measuring successful captures out of total attacks (pecks, probes, or dunks)
per 20-second video. To test variation in microplastic concentrations in sand, water, and prey across the
three sampling locations, a one-way ANOVA will be performed. A Pearson’s correlation test will then be
conducted to assess the correlation between the foraging success rates of sanderlings and the microplastic
levels in sand, water, and prey items across the different locations. A regression analysis will also be used
to test a for a positive correlation between foraging success and microplastic concentrations. By integrating
environemtnal contamination levels with behavioral data and employing statistical analyses to evaluate the
relationships, this study will provide insight into whether microplastic pollution alters shorebird foraging
efficiency, opening up further research on how sanderlings may be increasing their microplastic consumption
in response to rising microplastic contamination.

```{r}
MoleCrabMP <- read_csv("data/MoleCrabMP.csv")
```
